Core_Mascotas/Core_Mascotas/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Mascotas.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Mascota> Mascota { get; set; }
    }
}

Core_Mascotas/Core_Mascotas/Models/ErrorViewModel.cs
using System;

namespace Core_Mascotas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Core_Mascotas/Core_Mascotas/Models/Mascota.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Mascotas.Models
{
    public class Mascota
    {
        [Key]
        public int IdMascota { get; set; }

        [Required(ErrorMessage = "Ingrese el nombre de la mascota")]
        [Display(Name = "Nombre de la mascota")]
        public string NombreMascota { get; set; }

        [Required(ErrorMessage = "Ingrese la raza")]
        [Display(Name = "Raza")]
        public string RazaMascota { get; set; }

        [Required(ErrorMessage = "Ingrese la edad")]
        [Display(Name = "Edad")]
        [Range(0, 25)]
        public int EdadMascota { get; set; }

        [Required(ErrorMessage = "Ingrese número de ficha")]
        [Display(Name = "No. Ficha")]
        [Range(0, 25)]
        public int NumeroFicha { get; set; }

        [Required(ErrorMessage = "Ingrese el nombre del veterinario que atendera")]
        [Display(Name = "Veterinario")]
        public string Vet { get; set; }
    }
}

Core_Mascotas/Core_Mascotas/Controllers/MascotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Core_Mascotas.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Core_Mascotas.Controllers
{
    public class MascotaController : Controller
    {
        private readonly ApplicationDbContext _db;
        public MascotaController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index() // 1) Crear vista
        {
            var displaydata = _db.Mascota.ToList();
            return View(displaydata);
        }

        [HttpGet] //Barra de busqueda
        public async Task<IActionResult> Index(string petSearch)
        {
            ViewData["GetMascotaDetails"] = petSearch;
            var petquery = from x in _db.Mascota select x;
            if (!String.IsNullOrEmpty(petSearch))
            {
                petquery = petquery.Where(x => x.NombreMascota.Contains(petSearch) || x.Vet.Contains(petSearch));
            }
            return View(await petquery.AsNoTracking().ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }


        //2)Crear registro
        [HttpPost]
        public async Task<IActionResult> Create(Mascota nPet)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nPet);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(nPet);
        }

        //3) Detalles del resgitro
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getPetDetail = await _db.Mascota.FindAsync(id);
            return View(getPetDetail);
        }

        //4)Editar cliente
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getPetDetail = await _db.Mascota.FindAsync(id);
            return View(getPetDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Mascota oldPet)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldPet);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldPet);
        }

        //5)Eliminar cliente
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getPetDetails = await _db.Mascota.FindAsync(id);
            return View(getPetDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getPetdetail = await _db.Mascota.FindAsync(id);
            _db.Mascota.Remove(getPetdetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


    }
}

Core_Mascotas/Core_Mascotas/Views/Mascota/Create.cshtml
@model Core_Mascotas.Models.Mascota

@{
    ViewData["Title"] = "Create";
}

<h1>Crear un nuevo registro</h1>

<h4>Mickey's Cares</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <!--<div class="form-group">
                <label asp-for="IdMascota" class="control-label"></label>
                <input asp-for="IdMascota" class="form-control" />
                <span asp-validation-for="IdMascota" class="text-danger"></span>
            </div>-->
            <div class="form-group">
                <label asp-for="NombreMascota" class="control-label"></label>
                <input asp-for="NombreMascota" class="form-control" />
                <span asp-validation-for="NombreMascota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RazaMascota" class="control-label"></label>
                <input asp-for="RazaMascota" class="form-control" />
                <span asp-validation-for="RazaMascota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EdadMascota" class="control-label"></label>
                <input asp-for="EdadMascota" class="form-control" />
                <span asp-validation-for="EdadMascota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroFicha" class="control-label"></label>
                <input asp-for="NumeroFicha" class="form-control" />
                <span asp-validation-for="NumeroFicha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vet" class="control-label"></label>
                <input asp-for="Vet" class="form-control" />
                <span asp-validation-for="Vet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Mascotas/Core_Mascotas/Views/Mascota/Delete.cshtml
@model Core_Mascotas.Models.Mascota

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>¿Desea eliminar este registro?</h3>
<div>
    <h4>Mickey's Cares</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdMascota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdMascota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreMascota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreMascota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RazaMascota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RazaMascota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EdadMascota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EdadMascota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroFicha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroFicha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vet)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar a la lista</a>
    </form>
</div>

Core_Mascotas/Core_Mascotas/Views/Mascota/Detail.cshtml
@model Core_Mascotas.Models.Mascota

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles</h1>

<div>
    <h4>Mickey's Cares</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdMascota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdMascota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreMascota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreMascota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RazaMascota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RazaMascota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EdadMascota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EdadMascota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroFicha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroFicha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vet)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Regresar a la lista</a>
</div>

Core_Mascotas/Core_Mascotas/Views/Mascota/Edit.cshtml
@model Core_Mascotas.Models.Mascota

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar registro</h1>

<h4>Mickey's Cares</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdMascota" class="control-label"></label>
                <input asp-for="IdMascota" class="form-control" readonly/>
                <span asp-validation-for="IdMascota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreMascota" class="control-label"></label>
                <input asp-for="NombreMascota" class="form-control" />
                <span asp-validation-for="NombreMascota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RazaMascota" class="control-label"></label>
                <input asp-for="RazaMascota" class="form-control" />
                <span asp-validation-for="RazaMascota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EdadMascota" class="control-label"></label>
                <input asp-for="EdadMascota" class="form-control" />
                <span asp-validation-for="EdadMascota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroFicha" class="control-label"></label>
                <input asp-for="NumeroFicha" class="form-control" />
                <span asp-validation-for="NumeroFicha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vet" class="control-label"></label>
                <input asp-for="Vet" class="form-control" />
                <span asp-validation-for="Vet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Mascotas/Core_Mascotas/Views/Mascota/Index.cshtml
@model IEnumerable<Core_Mascotas.Models.Mascota>

@{
    ViewData["Title"] = "Index";
}

<h1>Mickey's Cares </h1>

<p>
    <a asp-action="Create">Crear un nuevo registro</a>
</p>


<form asp-action="Index" method="get">
    <p>
        <input type="search" placeholder="Ingresa nombre de la mascota o veterinario..." name="petSearch" value="@ViewData["GetMascotaDetails"]" style="width:500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index">Ver todos</a>
    </p>
 </form>

    <table class="table">
        <thead>

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IdMascota)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NombreMascota)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RazaMascota)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EdadMascota)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumeroFicha)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vet)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdMascota)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NombreMascota)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RazaMascota)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EdadMascota)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumeroFicha)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Vet)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id = item.IdMascota }, new { @class = "btn btn-primary" }) |
                        @Html.ActionLink("Detalles", "Detail", new { id = item.IdMascota }, new { @class = "btn btn-success" }) |
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.IdMascota }, new { @class = "btn btn-danger" })
                    </td>
                </tr>
            }
        </tbody>
    </table>

Core_Mascotas/Core_Mascotas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core_Mascotas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Mascota" asp-action="Index">Core_Mascotas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mascota" asp-action="Index">Home</a>
                        </li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Mickey's Cares
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>